<?php

namespace Market3w\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppointmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentRepository extends EntityRepository
{
    public function findAppointmentForProspect($prospectId)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.prospect = :prospectId')
            ->setParameter('prospectId', $prospectId);
                
        return $qb->getQuery()->getOneOrNullResult();
    }
    
}
