<?php

namespace Market3w\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends EntityRepository
{
    public function findHistoryForDate($clientId, $date)
    {
        $qb = $this->createQueryBuilder('h')
            ->where('h.client = :clientId')
            ->andWhere('h.date LIKE :date')
            ->setParameter('clientId', $clientId)
            ->setParameter('date', '%'.$date.'%');
                
        return $qb->getQuery()->getOneOrNullResult();
    }
}
