<?php

namespace Market3w\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HourRepository extends EntityRepository
{
}
