<?php

namespace Market3w\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    
    public function findRandomProjects($nb)
    {
        $projects = $this->createQueryBuilder('p')
                ->getQuery()
                ->getResult();
        
        $selection = array_rand($projects, $nb);
        
        foreach ($selection as $selected){
            $randomProjects[] = $projects[$selected];
        }
        
        return $randomProjects;
    }
}
