market3wsite:
    resource: "@Market3wSiteBundle/Controller/"
    type:     annotation
    prefix:   /
    
news_rss_index:
    path : /rss
    defaults: { _controller: Market3wSiteBundle:Intranet/News:Index, _format: xml }
    requirements:
        _format: rss
                
oneNews_rss_show:
    path : /rss/{id}
    defaults: { _controller: Market3wSiteBundle:Intranet/News:Show, _format: xml }
    requirements:
        _format: rss
        id: \d+
        
api_get_appointments:
    path: /api/web_marketeur/{id}/appointments
    defaults: { _controller: Market3wSiteBundle:Intranet/Agenda:Index, _format: json }
    requirements:
        _method: GET
        id: \d+

api_get_appointment:
    path: /api/appointment/{id}
    defaults: { _controller: Market3wSiteBundle:Intranet/Agenda:Show, _format: json }
    requirements:
        _method: GET
        id: \d+
        
api_edit_appointment:
    path: /api/appointment/edit
    defaults: { _controller: Market3wSiteBundle:Intranet/Agenda:Put, _format: json }
    requirements:
        _method: PUT
        
api_confirm_appointment:
    path: /api/appointment/confirm
    defaults: { _controller: Market3wSiteBundle:Intranet/Agenda:Confirm, _format: json }
    requirements:
        _method: PUT
        
api_get_clients:
    path: /api/web_marketeur/{id}/clients
    defaults: { _controller: Market3wSiteBundle:Intranet/WebMarketeur:Index, _format: json }
    requirements:
        _method: GET
        id: \d+

api_get_client:
    path: /api/client/{id}
    defaults: { _controller: Market3wSiteBundle:Intranet/WebMarketeur:Show, _format: json }
    requirements:
        _method: GET
        id: \d+
        
api_post_client:
    path: /api/add/client
    defaults: { _controller: Market3wSiteBundle:Intranet/WebMarketeur:PostClient, _format: json }
    requirements:
        _method: POST
        id: \d+

# FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

