services:
    market3w_user.registration.form.type:
        class: Market3w\SiteBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: market3w_user_registration }
    market3w_user.profile.form.type:
        class: Market3w\SiteBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: market3w_user_profile }
    form.type.appointment:
        class: Market3w\SiteBundle\Form\Type\AppointmentType
        arguments: ["@security.context"]
        tags:
            - { name: form.type, alias: appointment_type }
